[package]
name = "thmbox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["cargo"] }
get-cookies = { git = "https://github.com/ChrisPritchard/get-cookies-rs.git" }
tokio = { version = "1.38.0", features = ["macros"] }
